distribution_code_name: "ibus-rime"
distribution_name: Rime
distribution_version: 1.5.0
install_time: "Mon Jun  7 16:09:17 2021"
installation_id: "7c4ba820-edde-4922-b2ad-dd4fdcc20ca3"
rime_version: 1.7.3