local indent = 4
vim.opt.inccommand = "split" -- "for incsearch while sub
vim.opt.clipboard = "unnamedplus"                    -- have vim use OS clipboard
vim.opt.completeopt = "menuone,noinsert,noselect"    -- autocomplete options
vim.opt.expandtab = true                             -- expand tabs into spaces
vim.opt.autoindent = true
vim.opt.smarttab = true
vim.opt.ignorecase = true                            -- search case insensitive
vim.opt.smartcase = true
vim.opt.termguicolors = true                         -- enable true color
vim.opt.tabstop = indent
vim.opt.shiftwidth = indent
vim.opt.pumheight = 12                               -- maximum autocomplete popup height
vim.opt.timeoutlen = 200                             -- note that this controls which-key.nvim
vim.opt.textwidth = 100
vim.opt.splitright = true                            -- open splits on the right by default
vim.opt.number=true
vim.opt.laststatus=2
vim.opt.undofile = true
vim.opt.undodir = vim.fn.expand('~/.vim/undodir')
vim.opt.background="dark"
vim.cmd('colorscheme gruvbox')
